( cd usr/lib ; rm -rf librz_analysis.so )
( cd usr/lib ; ln -sf librz_analysis.so.0.5 librz_analysis.so )
( cd usr/lib ; rm -rf librz_analysis.so.0.5 )
( cd usr/lib ; ln -sf librz_analysis.so.0.5.2 librz_analysis.so.0.5 )
( cd usr/lib ; rm -rf librz_asm.so )
( cd usr/lib ; ln -sf librz_asm.so.0.5 librz_asm.so )
( cd usr/lib ; rm -rf librz_asm.so.0.5 )
( cd usr/lib ; ln -sf librz_asm.so.0.5.2 librz_asm.so.0.5 )
( cd usr/lib ; rm -rf librz_bin.so )
( cd usr/lib ; ln -sf librz_bin.so.0.5 librz_bin.so )
( cd usr/lib ; rm -rf librz_bin.so.0.5 )
( cd usr/lib ; ln -sf librz_bin.so.0.5.2 librz_bin.so.0.5 )
( cd usr/lib ; rm -rf librz_bp.so )
( cd usr/lib ; ln -sf librz_bp.so.0.5 librz_bp.so )
( cd usr/lib ; rm -rf librz_bp.so.0.5 )
( cd usr/lib ; ln -sf librz_bp.so.0.5.2 librz_bp.so.0.5 )
( cd usr/lib ; rm -rf librz_config.so )
( cd usr/lib ; ln -sf librz_config.so.0.5 librz_config.so )
( cd usr/lib ; rm -rf librz_config.so.0.5 )
( cd usr/lib ; ln -sf librz_config.so.0.5.2 librz_config.so.0.5 )
( cd usr/lib ; rm -rf librz_cons.so )
( cd usr/lib ; ln -sf librz_cons.so.0.5 librz_cons.so )
( cd usr/lib ; rm -rf librz_cons.so.0.5 )
( cd usr/lib ; ln -sf librz_cons.so.0.5.2 librz_cons.so.0.5 )
( cd usr/lib ; rm -rf librz_core.so )
( cd usr/lib ; ln -sf librz_core.so.0.5 librz_core.so )
( cd usr/lib ; rm -rf librz_core.so.0.5 )
( cd usr/lib ; ln -sf librz_core.so.0.5.2 librz_core.so.0.5 )
( cd usr/lib ; rm -rf librz_crypto.so )
( cd usr/lib ; ln -sf librz_crypto.so.0.5 librz_crypto.so )
( cd usr/lib ; rm -rf librz_crypto.so.0.5 )
( cd usr/lib ; ln -sf librz_crypto.so.0.5.2 librz_crypto.so.0.5 )
( cd usr/lib ; rm -rf librz_debug.so )
( cd usr/lib ; ln -sf librz_debug.so.0.5 librz_debug.so )
( cd usr/lib ; rm -rf librz_debug.so.0.5 )
( cd usr/lib ; ln -sf librz_debug.so.0.5.2 librz_debug.so.0.5 )
( cd usr/lib ; rm -rf librz_demangler.so )
( cd usr/lib ; ln -sf librz_demangler.so.0.5 librz_demangler.so )
( cd usr/lib ; rm -rf librz_demangler.so.0.5 )
( cd usr/lib ; ln -sf librz_demangler.so.0.5.2 librz_demangler.so.0.5 )
( cd usr/lib ; rm -rf librz_diff.so )
( cd usr/lib ; ln -sf librz_diff.so.0.5 librz_diff.so )
( cd usr/lib ; rm -rf librz_diff.so.0.5 )
( cd usr/lib ; ln -sf librz_diff.so.0.5.2 librz_diff.so.0.5 )
( cd usr/lib ; rm -rf librz_egg.so )
( cd usr/lib ; ln -sf librz_egg.so.0.5 librz_egg.so )
( cd usr/lib ; rm -rf librz_egg.so.0.5 )
( cd usr/lib ; ln -sf librz_egg.so.0.5.2 librz_egg.so.0.5 )
( cd usr/lib ; rm -rf librz_flag.so )
( cd usr/lib ; ln -sf librz_flag.so.0.5 librz_flag.so )
( cd usr/lib ; rm -rf librz_flag.so.0.5 )
( cd usr/lib ; ln -sf librz_flag.so.0.5.2 librz_flag.so.0.5 )
( cd usr/lib ; rm -rf librz_hash.so )
( cd usr/lib ; ln -sf librz_hash.so.0.5 librz_hash.so )
( cd usr/lib ; rm -rf librz_hash.so.0.5 )
( cd usr/lib ; ln -sf librz_hash.so.0.5.2 librz_hash.so.0.5 )
( cd usr/lib ; rm -rf librz_il.so )
( cd usr/lib ; ln -sf librz_il.so.0.5 librz_il.so )
( cd usr/lib ; rm -rf librz_il.so.0.5 )
( cd usr/lib ; ln -sf librz_il.so.0.5.2 librz_il.so.0.5 )
( cd usr/lib ; rm -rf librz_io.so )
( cd usr/lib ; ln -sf librz_io.so.0.5 librz_io.so )
( cd usr/lib ; rm -rf librz_io.so.0.5 )
( cd usr/lib ; ln -sf librz_io.so.0.5.2 librz_io.so.0.5 )
( cd usr/lib ; rm -rf librz_lang.so )
( cd usr/lib ; ln -sf librz_lang.so.0.5 librz_lang.so )
( cd usr/lib ; rm -rf librz_lang.so.0.5 )
( cd usr/lib ; ln -sf librz_lang.so.0.5.2 librz_lang.so.0.5 )
( cd usr/lib ; rm -rf librz_magic.so )
( cd usr/lib ; ln -sf librz_magic.so.0.5 librz_magic.so )
( cd usr/lib ; rm -rf librz_magic.so.0.5 )
( cd usr/lib ; ln -sf librz_magic.so.0.5.2 librz_magic.so.0.5 )
( cd usr/lib ; rm -rf librz_main.so )
( cd usr/lib ; ln -sf librz_main.so.0.5 librz_main.so )
( cd usr/lib ; rm -rf librz_main.so.0.5 )
( cd usr/lib ; ln -sf librz_main.so.0.5.2 librz_main.so.0.5 )
( cd usr/lib ; rm -rf librz_parse.so )
( cd usr/lib ; ln -sf librz_parse.so.0.5 librz_parse.so )
( cd usr/lib ; rm -rf librz_parse.so.0.5 )
( cd usr/lib ; ln -sf librz_parse.so.0.5.2 librz_parse.so.0.5 )
( cd usr/lib ; rm -rf librz_reg.so )
( cd usr/lib ; ln -sf librz_reg.so.0.5 librz_reg.so )
( cd usr/lib ; rm -rf librz_reg.so.0.5 )
( cd usr/lib ; ln -sf librz_reg.so.0.5.2 librz_reg.so.0.5 )
( cd usr/lib ; rm -rf librz_search.so )
( cd usr/lib ; ln -sf librz_search.so.0.5 librz_search.so )
( cd usr/lib ; rm -rf librz_search.so.0.5 )
( cd usr/lib ; ln -sf librz_search.so.0.5.2 librz_search.so.0.5 )
( cd usr/lib ; rm -rf librz_sign.so )
( cd usr/lib ; ln -sf librz_sign.so.0.5 librz_sign.so )
( cd usr/lib ; rm -rf librz_sign.so.0.5 )
( cd usr/lib ; ln -sf librz_sign.so.0.5.2 librz_sign.so.0.5 )
( cd usr/lib ; rm -rf librz_socket.so )
( cd usr/lib ; ln -sf librz_socket.so.0.5 librz_socket.so )
( cd usr/lib ; rm -rf librz_socket.so.0.5 )
( cd usr/lib ; ln -sf librz_socket.so.0.5.2 librz_socket.so.0.5 )
( cd usr/lib ; rm -rf librz_syscall.so )
( cd usr/lib ; ln -sf librz_syscall.so.0.5 librz_syscall.so )
( cd usr/lib ; rm -rf librz_syscall.so.0.5 )
( cd usr/lib ; ln -sf librz_syscall.so.0.5.2 librz_syscall.so.0.5 )
( cd usr/lib ; rm -rf librz_type.so )
( cd usr/lib ; ln -sf librz_type.so.0.5 librz_type.so )
( cd usr/lib ; rm -rf librz_type.so.0.5 )
( cd usr/lib ; ln -sf librz_type.so.0.5.2 librz_type.so.0.5 )
( cd usr/lib ; rm -rf librz_util.so )
( cd usr/lib ; ln -sf librz_util.so.0.5 librz_util.so )
( cd usr/lib ; rm -rf librz_util.so.0.5 )
( cd usr/lib ; ln -sf librz_util.so.0.5.2 librz_util.so.0.5 )
