( cd usr/lib64 ; rm -rf libIPXACTmodels.so )
( cd usr/lib64 ; ln -sf libIPXACTmodels.so.1.0.0 libIPXACTmodels.so )
( cd usr/lib64 ; rm -rf libIPXACTmodels.so.1 )
( cd usr/lib64 ; ln -sf libIPXACTmodels.so.1.0.0 libIPXACTmodels.so.1 )
( cd usr/lib64 ; rm -rf libIPXACTmodels.so.1.0 )
( cd usr/lib64 ; ln -sf libIPXACTmodels.so.1.0.0 libIPXACTmodels.so.1.0 )
( cd usr/lib64 ; rm -rf libKactusAPI.so )
( cd usr/lib64 ; ln -sf libKactusAPI.so.1.0.0 libKactusAPI.so )
( cd usr/lib64 ; rm -rf libKactusAPI.so.1 )
( cd usr/lib64 ; ln -sf libKactusAPI.so.1.0.0 libKactusAPI.so.1 )
( cd usr/lib64 ; rm -rf libKactusAPI.so.1.0 )
( cd usr/lib64 ; ln -sf libKactusAPI.so.1.0.0 libKactusAPI.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libPadsPartGenerator.so )
( cd usr/share/kactus2/plugins ; ln -sf libPadsPartGenerator.so.1.0.0 libPadsPartGenerator.so )
( cd usr/share/kactus2/plugins ; rm -rf libPadsPartGenerator.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libPadsPartGenerator.so.1.0.0 libPadsPartGenerator.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libPadsPartGenerator.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libPadsPartGenerator.so.1.0.0 libPadsPartGenerator.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libSVDGeneratorPlugin.so )
( cd usr/share/kactus2/plugins ; ln -sf libSVDGeneratorPlugin.so.1.0.0 libSVDGeneratorPlugin.so )
( cd usr/share/kactus2/plugins ; rm -rf libSVDGeneratorPlugin.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libSVDGeneratorPlugin.so.1.0.0 libSVDGeneratorPlugin.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libSVDGeneratorPlugin.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libSVDGeneratorPlugin.so.1.0.0 libSVDGeneratorPlugin.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libVHDLimport.so )
( cd usr/share/kactus2/plugins ; ln -sf libVHDLimport.so.1.0.0 libVHDLimport.so )
( cd usr/share/kactus2/plugins ; rm -rf libVHDLimport.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libVHDLimport.so.1.0.0 libVHDLimport.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libVHDLimport.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libVHDLimport.so.1.0.0 libVHDLimport.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogGeneratorPlugin.so )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogGeneratorPlugin.so.1.0.0 libVerilogGeneratorPlugin.so )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogGeneratorPlugin.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogGeneratorPlugin.so.1.0.0 libVerilogGeneratorPlugin.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogGeneratorPlugin.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogGeneratorPlugin.so.1.0.0 libVerilogGeneratorPlugin.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogImport.so )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogImport.so.1.0.0 libVerilogImport.so )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogImport.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogImport.so.1.0.0 libVerilogImport.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogImport.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogImport.so.1.0.0 libVerilogImport.so.1.0 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogIncludeImport.so )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogIncludeImport.so.1.0.0 libVerilogIncludeImport.so )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogIncludeImport.so.1 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogIncludeImport.so.1.0.0 libVerilogIncludeImport.so.1 )
( cd usr/share/kactus2/plugins ; rm -rf libVerilogIncludeImport.so.1.0 )
( cd usr/share/kactus2/plugins ; ln -sf libVerilogIncludeImport.so.1.0.0 libVerilogIncludeImport.so.1.0 )
