( cd opt/llvm-mingw/aarch64-w64-mingw32 ; rm -rf include )
( cd opt/llvm-mingw/aarch64-w64-mingw32 ; ln -sf ../generic-w64-mingw32/include include )
( cd opt/llvm-mingw/arm64ec-w64-mingw32 ; rm -rf include )
( cd opt/llvm-mingw/arm64ec-w64-mingw32 ; ln -sf ../generic-w64-mingw32/include include )
( cd opt/llvm-mingw/armv7-w64-mingw32 ; rm -rf include )
( cd opt/llvm-mingw/armv7-w64-mingw32 ; ln -sf ../generic-w64-mingw32/include include )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; ln -sf aarch64-w64-windows-gnu.cfg aarch64-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line aarch64-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar aarch64-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps aarch64-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool aarch64-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh aarch64-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar aarch64-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib aarch64-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm aarch64-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy aarch64-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh aarch64-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib aarch64-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf aarch64-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size aarch64-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings aarch64-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip aarch64-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl aarch64-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres aarch64-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line aarch64-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar aarch64-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps aarch64-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool aarch64-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh aarch64-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh aarch64-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar aarch64-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib aarch64-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm aarch64-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy aarch64-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh aarch64-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib aarch64-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf aarch64-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size aarch64-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings aarch64-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip aarch64-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl aarch64-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; rm -rf aarch64-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres aarch64-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; rm -rf amdgpu-arch )
( cd opt/llvm-mingw/bin ; ln -sf offload-arch amdgpu-arch )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; ln -sf arm64ec-w64-windows-gnu.cfg arm64ec-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line arm64ec-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar arm64ec-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps arm64ec-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool arm64ec-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh arm64ec-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar arm64ec-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib arm64ec-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm arm64ec-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy arm64ec-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh arm64ec-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib arm64ec-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf arm64ec-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size arm64ec-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings arm64ec-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip arm64ec-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl arm64ec-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres arm64ec-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line arm64ec-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar arm64ec-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps arm64ec-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool arm64ec-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh arm64ec-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh arm64ec-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar arm64ec-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib arm64ec-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm arm64ec-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy arm64ec-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh arm64ec-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib arm64ec-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf arm64ec-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size arm64ec-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings arm64ec-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip arm64ec-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl arm64ec-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; rm -rf arm64ec-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres arm64ec-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; rm -rf armv7-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; ln -sf armv7-w64-windows-gnu.cfg armv7-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line armv7-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar armv7-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps armv7-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool armv7-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh armv7-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar armv7-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib armv7-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm armv7-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy armv7-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh armv7-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib armv7-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf armv7-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size armv7-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings armv7-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip armv7-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl armv7-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres armv7-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line armv7-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar armv7-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps armv7-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool armv7-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh armv7-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh armv7-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar armv7-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib armv7-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm armv7-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy armv7-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh armv7-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib armv7-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf armv7-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size armv7-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings armv7-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip armv7-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl armv7-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; rm -rf armv7-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres armv7-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; rm -rf clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-22 clang )
( cd opt/llvm-mingw/bin ; rm -rf clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang clang++ )
( cd opt/llvm-mingw/bin ; rm -rf clang-cl )
( cd opt/llvm-mingw/bin ; ln -sf clang clang-cl )
( cd opt/llvm-mingw/bin ; rm -rf clang-cpp )
( cd opt/llvm-mingw/bin ; ln -sf clang clang-cpp )
( cd opt/llvm-mingw/bin ; rm -rf clang-offload-packager )
( cd opt/llvm-mingw/bin ; ln -sf llvm-offload-binary clang-offload-packager )
( cd opt/llvm-mingw/bin ; rm -rf i686-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-windows-gnu.cfg i686-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line i686-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar i686-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps i686-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool i686-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh i686-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar i686-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib i686-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm i686-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy i686-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh i686-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib i686-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf i686-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size i686-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings i686-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip i686-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres i686-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line i686-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar i686-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps i686-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool i686-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh i686-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh i686-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar i686-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib i686-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm i686-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy i686-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh i686-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib i686-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf i686-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size i686-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings i686-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip i686-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl i686-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; rm -rf i686-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres i686-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; rm -rf ld.lld )
( cd opt/llvm-mingw/bin ; ln -sf lld ld.lld )
( cd opt/llvm-mingw/bin ; rm -rf ld64.lld )
( cd opt/llvm-mingw/bin ; ln -sf lld ld64.lld )
( cd opt/llvm-mingw/bin ; rm -rf lld-link )
( cd opt/llvm-mingw/bin ; ln -sf lld lld-link )
( cd opt/llvm-mingw/bin ; rm -rf llvm-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-symbolizer llvm-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf llvm-bitcode-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy llvm-bitcode-strip )
( cd opt/llvm-mingw/bin ; rm -rf llvm-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar llvm-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf llvm-install-name-tool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy llvm-install-name-tool )
( cd opt/llvm-mingw/bin ; rm -rf llvm-lib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar llvm-lib )
( cd opt/llvm-mingw/bin ; rm -rf llvm-ml64 )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ml llvm-ml64 )
( cd opt/llvm-mingw/bin ; rm -rf llvm-otool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objdump llvm-otool )
( cd opt/llvm-mingw/bin ; rm -rf llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf llvm-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readobj llvm-readelf )
( cd opt/llvm-mingw/bin ; rm -rf llvm-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy llvm-strip )
( cd opt/llvm-mingw/bin ; rm -rf llvm-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-rc llvm-windres )
( cd opt/llvm-mingw/bin ; rm -rf nvptx-arch )
( cd opt/llvm-mingw/bin ; ln -sf offload-arch nvptx-arch )
( cd opt/llvm-mingw/bin ; rm -rf wasm-ld )
( cd opt/llvm-mingw/bin ; ln -sf lld wasm-ld )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; ln -sf x86_64-w64-windows-gnu.cfg x86_64-pc-windows-gnu.cfg )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line x86_64-w64-mingw32-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar x86_64-w64-mingw32-ar )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-as )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-c++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-clang )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps x86_64-w64-mingw32-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool x86_64-w64-mingw32-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-g++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32-gcc )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh x86_64-w64-mingw32-ld )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar x86_64-w64-mingw32-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib x86_64-w64-mingw32-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm x86_64-w64-mingw32-nm )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy x86_64-w64-mingw32-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh x86_64-w64-mingw32-objdump )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib x86_64-w64-mingw32-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf x86_64-w64-mingw32-readelf )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size x86_64-w64-mingw32-size )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings x86_64-w64-mingw32-strings )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip x86_64-w64-mingw32-strip )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl x86_64-w64-mingw32-widl )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres x86_64-w64-mingw32-windres )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; ln -sf llvm-addr2line x86_64-w64-mingw32uwp-addr2line )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar x86_64-w64-mingw32uwp-ar )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-as )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-c++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-clang )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-clang++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; ln -sf clang-scan-deps x86_64-w64-mingw32uwp-clang-scan-deps )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; ln -sf llvm-dlltool x86_64-w64-mingw32uwp-dlltool )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-g++ )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; ln -sf clang-target-wrapper.sh x86_64-w64-mingw32uwp-gcc )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; ln -sf ld-wrapper.sh x86_64-w64-mingw32uwp-ld )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ar x86_64-w64-mingw32uwp-llvm-ar )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib x86_64-w64-mingw32uwp-llvm-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; ln -sf llvm-nm x86_64-w64-mingw32uwp-nm )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; ln -sf llvm-objcopy x86_64-w64-mingw32uwp-objcopy )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; ln -sf objdump-wrapper.sh x86_64-w64-mingw32uwp-objdump )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; ln -sf llvm-ranlib x86_64-w64-mingw32uwp-ranlib )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; ln -sf llvm-readelf x86_64-w64-mingw32uwp-readelf )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; ln -sf llvm-size x86_64-w64-mingw32uwp-size )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strings x86_64-w64-mingw32uwp-strings )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; ln -sf llvm-strip x86_64-w64-mingw32uwp-strip )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; ln -sf i686-w64-mingw32-widl x86_64-w64-mingw32uwp-widl )
( cd opt/llvm-mingw/bin ; rm -rf x86_64-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/bin ; ln -sf llvm-windres x86_64-w64-mingw32uwp-windres )
( cd opt/llvm-mingw/i686-w64-mingw32 ; rm -rf include )
( cd opt/llvm-mingw/i686-w64-mingw32 ; ln -sf ../generic-w64-mingw32/include include )
( cd opt/llvm-mingw/lib ; rm -rf libLLVM-22-rc1.so )
( cd opt/llvm-mingw/lib ; ln -sf libLLVM.so.22.1-rc1 libLLVM-22-rc1.so )
( cd opt/llvm-mingw/lib ; rm -rf libLLVM.so )
( cd opt/llvm-mingw/lib ; ln -sf libLLVM.so.22.1-rc1 libLLVM.so )
( cd opt/llvm-mingw/lib ; rm -rf libLTO.so )
( cd opt/llvm-mingw/lib ; ln -sf libLTO.so.22.1-rc1 libLTO.so )
( cd opt/llvm-mingw/lib ; rm -rf libRemarks.so )
( cd opt/llvm-mingw/lib ; ln -sf libRemarks.so.22.1-rc1 libRemarks.so )
( cd opt/llvm-mingw/lib ; rm -rf libclang-cpp.so )
( cd opt/llvm-mingw/lib ; ln -sf libclang-cpp.so.22.1-rc1 libclang-cpp.so )
( cd opt/llvm-mingw/lib ; rm -rf libclang.so )
( cd opt/llvm-mingw/lib ; ln -sf libclang.so.22.1-rc1 libclang.so )
( cd opt/llvm-mingw/lib ; rm -rf libclang.so.22.1-rc1 )
( cd opt/llvm-mingw/lib ; ln -sf libclang.so.22.1.0-rc1 libclang.so.22.1-rc1 )
( cd opt/llvm-mingw/lib ; rm -rf liblldb.so )
( cd opt/llvm-mingw/lib ; ln -sf liblldb.so.22.1-rc1 liblldb.so )
( cd opt/llvm-mingw/lib ; rm -rf liblldb.so.22.1-rc1 )
( cd opt/llvm-mingw/lib ; ln -sf liblldb.so.22.1.0-rc1 liblldb.so.22.1-rc1 )
( cd opt/llvm-mingw/lib ; rm -rf liblldbIntelFeatures.so )
( cd opt/llvm-mingw/lib ; ln -sf liblldbIntelFeatures.so.22.1-rc1 liblldbIntelFeatures.so )
( cd opt/llvm-mingw/lib/lua/5.4 ; rm -rf lldb.so )
( cd opt/llvm-mingw/lib/lua/5.4 ; ln -sf ../../liblldb.so lldb.so )
( cd opt/llvm-mingw/lib64/python3.12/site-packages/lldb ; rm -rf lldb-argdumper )
( cd opt/llvm-mingw/lib64/python3.12/site-packages/lldb ; ln -sf ../../../../bin/lldb-argdumper lldb-argdumper )
( cd opt/llvm-mingw/lib64/python3.12/site-packages/lldb/native ; rm -rf _lldb.abi3.so )
( cd opt/llvm-mingw/lib64/python3.12/site-packages/lldb/native ; ln -sf ../../../../../lib/liblldb.so _lldb.abi3.so )
( cd opt/llvm-mingw/x86_64-w64-mingw32 ; rm -rf include )
( cd opt/llvm-mingw/x86_64-w64-mingw32 ; ln -sf ../generic-w64-mingw32/include include )
