5c5
< PREFIX         = /usr/local
---
> PREFIX         = /usr
8c8
< LIBINSTALLDIR  = $(EPREFIX)/lib
---
> LIBINSTALLDIR  = $(EPREFIX)/lib64
10c10
< MANPREFIX      = $(PREFIX)/share
---
> MANPREFIX      = $(PREFIX)
