1823,1828c1823,1828
< 	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
< 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/sasm $(INSTALL_ROOT)/usr/bin/sasm
< 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/Linux/bin/fasm $(INSTALL_ROOT)/usr/bin/fasm
< 	-strip $(INSTALL_ROOT)/usr/bin/fasm
< 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/Linux/bin/listing $(INSTALL_ROOT)/usr/bin/listing
< 	-strip $(INSTALL_ROOT)/usr/bin/listing
---
> 	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(DESTDIR)$(INSTALL_ROOT)/usr/bin
> 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/sasm $(DESTDIR)$(INSTALL_ROOT)/usr/bin/sasm
> 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/Linux/bin/fasm $(DESTDIR)$(INSTALL_ROOT)/usr/bin/fasm
> 	-strip $(DESTDIR)/$(INSTALL_ROOT)/usr/bin/fasm
> 	$(QINSTALL_PROGRAM) /tmp/SBo/SASM-3.14.0/Linux/bin/listing $(DESTDIR)$(INSTALL_ROOT)/usr/bin/listing
> 	-strip $(DESTDIR)/$(INSTALL_ROOT)/usr/bin/listing
1838,1843c1838,1843
< 	@test -d $(INSTALL_ROOT)/usr/share/sasm/ || mkdir -p $(INSTALL_ROOT)/usr/share/sasm/
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/include $(INSTALL_ROOT)/usr/share/sasm/include
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/keys.ini $(INSTALL_ROOT)/usr/share/sasm/keys.ini
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/NASM $(INSTALL_ROOT)/usr/share/sasm/NASM
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/Projects $(INSTALL_ROOT)/usr/share/sasm/Projects
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/sasm.png $(INSTALL_ROOT)/usr/share/sasm/sasm.png
---
> 	@test -d $(INSTALL_ROOT)/usr/share/sasm/ || mkdir -p $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/include $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/include
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/keys.ini $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/keys.ini
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/NASM $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/NASM
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/Projects $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/Projects
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/sasm/sasm.png $(DESTDIR)$(INSTALL_ROOT)/usr/share/sasm/sasm.png
1855,1856c1855,1856
< 	@test -d $(INSTALL_ROOT)/usr/share/applications/ || mkdir -p $(INSTALL_ROOT)/usr/share/applications/
< 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/applications/sasm.desktop $(INSTALL_ROOT)/usr/share/applications/sasm.desktop
---
> 	@test -d $(INSTALL_ROOT)/usr/share/applications/ || mkdir -p $(DESTDIR)$(INSTALL_ROOT)/usr/share/applications/
> 	$(QINSTALL) /tmp/SBo/SASM-3.14.0/Linux/share/applications/sasm.desktop $(DESTDIR)$(INSTALL_ROOT)/usr/share/applications/sasm.desktop
