( cd usr/lib64 ; rm -rf libsharpyuv.so )
( cd usr/lib64 ; ln -sf libsharpyuv.so.0.1.2 libsharpyuv.so )
( cd usr/lib64 ; rm -rf libsharpyuv.so.0 )
( cd usr/lib64 ; ln -sf libsharpyuv.so.0.1.2 libsharpyuv.so.0 )
( cd usr/lib64 ; rm -rf libwebp.so )
( cd usr/lib64 ; ln -sf libwebp.so.7.2.0 libwebp.so )
( cd usr/lib64 ; rm -rf libwebp.so.7 )
( cd usr/lib64 ; ln -sf libwebp.so.7.2.0 libwebp.so.7 )
( cd usr/lib64 ; rm -rf libwebpdecoder.so )
( cd usr/lib64 ; ln -sf libwebpdecoder.so.3.2.0 libwebpdecoder.so )
( cd usr/lib64 ; rm -rf libwebpdecoder.so.3 )
( cd usr/lib64 ; ln -sf libwebpdecoder.so.3.2.0 libwebpdecoder.so.3 )
( cd usr/lib64 ; rm -rf libwebpdemux.so )
( cd usr/lib64 ; ln -sf libwebpdemux.so.2.0.17 libwebpdemux.so )
( cd usr/lib64 ; rm -rf libwebpdemux.so.2 )
( cd usr/lib64 ; ln -sf libwebpdemux.so.2.0.17 libwebpdemux.so.2 )
( cd usr/lib64 ; rm -rf libwebpmux.so )
( cd usr/lib64 ; ln -sf libwebpmux.so.3.1.2 libwebpmux.so )
( cd usr/lib64 ; rm -rf libwebpmux.so.3 )
( cd usr/lib64 ; ln -sf libwebpmux.so.3.1.2 libwebpmux.so.3 )
