( cd opt/wasi-sdk-21.0/bin ; rm -rf ar )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-ar ar )
( cd opt/wasi-sdk-21.0/bin ; rm -rf c++filt )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-cxxfilt c++filt )
( cd opt/wasi-sdk-21.0/bin ; rm -rf clang )
( cd opt/wasi-sdk-21.0/bin ; ln -sf clang-17 clang )
( cd opt/wasi-sdk-21.0/bin ; rm -rf clang++ )
( cd opt/wasi-sdk-21.0/bin ; ln -sf clang clang++ )
( cd opt/wasi-sdk-21.0/bin ; rm -rf clang-cl )
( cd opt/wasi-sdk-21.0/bin ; ln -sf clang clang-cl )
( cd opt/wasi-sdk-21.0/bin ; rm -rf clang-cpp )
( cd opt/wasi-sdk-21.0/bin ; ln -sf clang clang-cpp )
( cd opt/wasi-sdk-21.0/bin ; rm -rf ld.lld )
( cd opt/wasi-sdk-21.0/bin ; ln -sf lld ld.lld )
( cd opt/wasi-sdk-21.0/bin ; rm -rf ld64.lld )
( cd opt/wasi-sdk-21.0/bin ; ln -sf lld ld64.lld )
( cd opt/wasi-sdk-21.0/bin ; rm -rf lld-link )
( cd opt/wasi-sdk-21.0/bin ; ln -sf lld lld-link )
( cd opt/wasi-sdk-21.0/bin ; rm -rf llvm-ranlib )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-ar llvm-ranlib )
( cd opt/wasi-sdk-21.0/bin ; rm -rf llvm-strip )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-objcopy llvm-strip )
( cd opt/wasi-sdk-21.0/bin ; rm -rf nm )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-nm nm )
( cd opt/wasi-sdk-21.0/bin ; rm -rf objcopy )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-objcopy objcopy )
( cd opt/wasi-sdk-21.0/bin ; rm -rf objdump )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-objdump objdump )
( cd opt/wasi-sdk-21.0/bin ; rm -rf ranlib )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-ar ranlib )
( cd opt/wasi-sdk-21.0/bin ; rm -rf size )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-size size )
( cd opt/wasi-sdk-21.0/bin ; rm -rf strings )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-strings strings )
( cd opt/wasi-sdk-21.0/bin ; rm -rf strip )
( cd opt/wasi-sdk-21.0/bin ; ln -sf llvm-objcopy strip )
( cd opt/wasi-sdk-21.0/bin ; rm -rf wasm-ld )
( cd opt/wasi-sdk-21.0/bin ; ln -sf lld wasm-ld )
